### ISSUE TITLE
Add `CODEOWNERS` file

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/.github#25]
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

Rule:

```
*      @jbampton
```

Thanks.

**Comment by jbampton** [comment]
Hey @aniruddhaadak80 can you please add your comment here on this issue saying you want it.

Thanks.  Just admin work.

**Comment by aniruddhaadak80** [comment]
Assign this issue to me @jbampton .
