### ISSUE TITLE
README.md file should be inside root folder 

### ISSUE THREAD

**Issue by aniruddhaadak80** [brisbanesocialchess/.github#43]
README.md file should be in root folder like .github/README.md not .github/profile/README.md

**Comment by aniruddhaadak80** [comment]
Assign this me please @jbampton  . I am working on it .

**Comment by jbampton** [comment]
![Screenshot from 2024-10-28 19-01-49](https://github.com/user-attachments/assets/405c548f-9679-4ed3-a1b0-5741f79495bc)

This is not needed.  This is a special repo it is different

**Comment by aniruddhaadak80** [comment]
> ![Screenshot from 2024-10-28 19-01-49](https://private-user-images.githubusercontent.com/418747/380644379-405c548f-9679-4ed3-a1b0-5741f79495bc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMTEyMzUsIm5iZiI6MTczMDExMDkzNSwicGF0aCI6Ii80MTg3NDcvMzgwNjQ0Mzc5LTQwNWM1NDhmLTk2NzktNGVkMy1hMWIwLTU3NDFmNzk0OTViYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyOFQxMDIyMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04YWZmYWE5MzM0ZDU3MjczNGQ1ZDA0YjhlZTlhYjc3YTg2M2ZjYTc0MzMxMDFjYWE0MTJjYzM2MGFhM2U0ZDE0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.URK_CIQyppPcuzkhTHfVMTJ0KBrKOWTRAo-pBw5Q-aI)
> 
> This is not needed. This is a special repo it is different

Okey , I understnd .Thank you to clarify me.
