### ISSUE TITLE
Add and configure proselint

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/.github#46]
refs https://github.com/brisbanesocialchess/awesome-social-chess/issues/86

**Comment by aniruddhaadak80** [comment]
Assign this issue to me @jbampton  please  . Now I am doing to fix this .

**Comment by jbampton** [comment]
You are now assigned @aniruddhaadak80 thanks mate :+1:

**Comment by aniruddhaadak80** [comment]
Please review this #63
