### ISSUE TITLE
Thanks for joining - Instructions

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/.github#47]
We need some info added to the org homepage README about below:

```
You can set your membership in the Brisbane Social Chess GitHub Organization to public on the people page when logged in:

https://github.com/orgs/brisbanesocialchess/people

Please show your support for your new team :)

If you are a private member, the public including everyone else that is not in the team won't see that you are part of Brisbane Social Chess.
```

**Comment by Virtual4087** [comment]
Hey @jbampton I would like to do this

**Comment by jbampton** [comment]
@Virtual4087 you are now assigned thanks :+1:

**Comment by Virtual4087** [comment]
@jbampton should I add it at the bottom of the readme inside profile dir?

**Comment by jbampton** [comment]
> @jbampton should I add it at the bottom of the readme inside profile dir?

Hey @aniruddhaadak80 what do you think ?

**Comment by jbampton** [comment]
> @jbampton should I add it at the bottom of the readme inside profile dir?

Good to go @Virtual4087 

You can start now if you want thanks
