### ISSUE TITLE
Add Discord badge to README and info about Disco 

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/.github#48]
https://shields.io/badges/discord

Some info also needs to be added telling people they should join our new Discord server.

Thanks !!

**Comment by aniruddhaadak80** [comment]
Assign this issue to me @jbampton .

**Comment by jbampton** [comment]
Thanks @aniruddhaadak80 you are now assigned :+1:

**Comment by jbampton** [comment]
fixed by #59  thanks
