### ISSUE TITLE
Fix codespell pre-commit

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/.github#82]
https://github.com/brisbanesocialchess/.github/actions/runs/11576753832/job/32226483810?pr=78

**Comment by dhirajchaurasiya10** [comment]
@jbampton Can you explain briefly about the things to be done to solve this issue?

**Comment by jbampton** [comment]
@dhirajchaurasiya10 we are missing the `codespell.txt` file

```
- id: codespell
        name: Run codespell
        description: Check spelling with codespell
        args: [--ignore-words=.github/linters/codespell.txt]
```

**Comment by jbampton** [comment]
https://github.com/codespell-project/codespell?tab=readme-ov-file#ignoring-words

**Comment by jbampton** [comment]
https://github.com/brisbanesocialchess/.github/blob/main/.codespellrc

**Comment by dhirajchaurasiya10** [comment]
@jbampton Will adding codespell.txt solve this issue? If something more is needed please do describe me to be clear

**Comment by jbampton** [comment]
You will need to update the pre-commit config to add

`args: [--ignore-words=.github/linters/codespell.txt]`

for the codespell hook

**Comment by jbampton** [comment]
After you have done all that you can test on your local machine with pre-commit.

First install pre-commit

`pip install pre-commit`

The from the repo root run:

`pre-commit run --all-files`

See what happens

**Comment by dhirajchaurasiya10** [comment]
@jbampton I made few changes this might solve the issue. Do review once.
