### ISSUE TITLE
Fix Super-Linter `GitHub Actions` lint errors

### ISSUE THREAD

**Issue by jbampton** [brisbanesocialchess/.github#93]
Error run seen here:

https://github.com/brisbanesocialchess/.github/actions/runs/11571687097/job/32210100298?pr=63

This issue is just for fixing the GitHub Actions linter errors not the others.

**Comment by BaseMax** [comment]
On it

**Comment by jbampton** [comment]
![Screenshot from 2024-10-31 22-01-02](https://github.com/user-attachments/assets/0f87967c-9fab-4c35-bad1-4166c887ad03)

**Comment by jbampton** [comment]
Done thanks
